server.port=8085

#dijar98229@luhupo.com
#dijar98229@luhupo.comQ
# Database connection properties
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ep-falling-river-axu1wshl-pooler.c-4.us-east-2.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_n2bqHN7tTAYQ

# JPA properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.connection.CharSet=UTF-8
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true