# Database connection settings
#lemaces361@besteya.com
#lemaces361@besteya.comQ
hibernate.connection.url=jdbc:postgresql://ep-holy-hat-avwouly8-pooler.c-11.us-east-1.aws.neon.tech/neondb?charSet=UTF8
hibernate.connection.username=neondb_owner
hibernate.connection.password=npg_3pP7FerckgQj

# Echo all executed SQL to console
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true

# Automatically export the schema
#hibernate.hbm2ddl.auto=create
hibernate.hbm2ddl.auto=update