# Database connection settings
#sedirin983@dnsink.com
#sedirin983@dnsink.comQ
hibernate.connection.url=jdbc:postgresql://ep-square-night-ayve9qhe-pooler.c-5.us-east-2.aws.neon.tech/neondb?charSet=UTF8
hibernate.connection.username=neondb_owner
hibernate.connection.password=npg_7RModF6DCvmk

# Echo all executed SQL to console
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true

# Automatically export the schema
#hibernate.hbm2ddl.auto=create
hibernate.hbm2ddl.auto=update